
import javax.swing.JOptionPane;

/**
 *
 * @author dev.eltongustavo@gmail.com
 */

public class GameVelha extends javax.swing.JFrame {
    
    int contador;
    String[][] posicoes = new String[3][3];
    int contadorJogadas = 0;
    

    public GameVelha() {
        initComponents();
        this.setLocationRelativeTo(null);
        setarMatrizVazia();
        txtVez.setVisible(false); // Texto que deve iniciar apenas quando a partida começar
        desabilitarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn02 = new javax.swing.JToggleButton();
        btn00 = new javax.swing.JToggleButton();
        btn01 = new javax.swing.JToggleButton();
        btn11 = new javax.swing.JToggleButton();
        btn12 = new javax.swing.JToggleButton();
        btn21 = new javax.swing.JToggleButton();
        btn22 = new javax.swing.JToggleButton();
        btn10 = new javax.swing.JToggleButton();
        btn20 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        painelQuemComeca = new javax.swing.JPanel();
        qcX = new javax.swing.JRadioButton();
        qcO = new javax.swing.JRadioButton();
        btnStart = new javax.swing.JButton();
        jtQuemComeca = new javax.swing.JTextField();
        txtVez = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JOGO DA VELHA");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        btn02.setBackground(new java.awt.Color(0, 0, 0));
        btn02.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn02.setForeground(new java.awt.Color(255, 255, 255));
        btn02.setFocusable(false);
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn00.setBackground(new java.awt.Color(0, 0, 0));
        btn00.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn00.setForeground(new java.awt.Color(255, 255, 255));
        btn00.setFocusCycleRoot(true);
        btn00.setFocusable(false);
        btn00.setRequestFocusEnabled(false);
        btn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn00ActionPerformed(evt);
            }
        });

        btn01.setBackground(new java.awt.Color(0, 0, 0));
        btn01.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn01.setForeground(new java.awt.Color(255, 255, 255));
        btn01.setFocusable(false);
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn11.setBackground(new java.awt.Color(0, 0, 0));
        btn11.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn11.setForeground(new java.awt.Color(255, 255, 255));
        btn11.setFocusable(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setBackground(new java.awt.Color(0, 0, 0));
        btn12.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn12.setForeground(new java.awt.Color(255, 255, 255));
        btn12.setFocusable(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn21.setBackground(new java.awt.Color(0, 0, 0));
        btn21.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn21.setForeground(new java.awt.Color(255, 255, 255));
        btn21.setFocusable(false);
        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });

        btn22.setBackground(new java.awt.Color(0, 0, 0));
        btn22.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn22.setForeground(new java.awt.Color(255, 255, 255));
        btn22.setFocusable(false);
        btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn22ActionPerformed(evt);
            }
        });

        btn10.setBackground(new java.awt.Color(0, 0, 0));
        btn10.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn10.setForeground(new java.awt.Color(255, 255, 255));
        btn10.setFocusable(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn20.setBackground(new java.awt.Color(0, 0, 0));
        btn20.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btn20.setForeground(new java.awt.Color(255, 255, 255));
        btn20.setFocusable(false);
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        painelQuemComeca.setBackground(new java.awt.Color(102, 102, 102));
        painelQuemComeca.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "QUEM COMEÇA?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        painelQuemComeca.setForeground(new java.awt.Color(60, 63, 65));

        qcX.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        qcX.setForeground(new java.awt.Color(255, 255, 255));
        qcX.setText("X");
        qcX.setFocusable(false);
        qcX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qcXActionPerformed(evt);
            }
        });

        qcO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        qcO.setForeground(new java.awt.Color(255, 255, 255));
        qcO.setText("O");
        qcO.setFocusable(false);
        qcO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qcOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelQuemComecaLayout = new javax.swing.GroupLayout(painelQuemComeca);
        painelQuemComeca.setLayout(painelQuemComecaLayout);
        painelQuemComecaLayout.setHorizontalGroup(
            painelQuemComecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQuemComecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelQuemComecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qcX, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qcO, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        painelQuemComecaLayout.setVerticalGroup(
            painelQuemComecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelQuemComecaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(qcX, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qcO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("COMEÇAR PARTIDA");
        btnStart.setFocusable(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jtQuemComeca.setEditable(false);
        jtQuemComeca.setBackground(new java.awt.Color(0, 0, 0));
        jtQuemComeca.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jtQuemComeca.setForeground(new java.awt.Color(255, 255, 255));
        jtQuemComeca.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtVez.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtVez.setText("AGORA É A VEZ DO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtVez)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(painelQuemComeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jtQuemComeca, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(painelQuemComeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtVez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtQuemComeca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setarMatrizVazia(){
        for (int y = 0; y < 3; y++) {
            for (int x = 0; x < 3; x++) {
                posicoes[y][x] = "";
            }
        }
    }
    
    public void atualizarMatriz(){
        posicoes[0][0] = btn00.getText();
        posicoes[0][1] = btn01.getText();
        posicoes[0][2] = btn02.getText();
        posicoes[1][0] = btn10.getText();
        posicoes[1][1] = btn11.getText();
        posicoes[1][2] = btn12.getText();
        posicoes[2][0] = btn20.getText();
        posicoes[2][1] = btn21.getText();
        posicoes[2][2] = btn22.getText();
        contadorJogadas++;
    }
    
    public void testarVencedor(){
        for (int i = 0; i < 3; i++) {
            if ((posicoes[i][0] == posicoes[i][1] && posicoes[i][1] == posicoes[i][2]) && posicoes[i][i] != "") {
                mostrarVencedor(true);
                reset();
            }else if((posicoes[0][i] == posicoes[1][i] && posicoes[1][i] == posicoes[2][i]) && posicoes[i][i] != ""){
                mostrarVencedor(true);
                reset();
            }else if((posicoes[0][0] == posicoes[1][1] && posicoes[1][1] == posicoes[2][2]) && posicoes[1][1] != ""){
                mostrarVencedor(true);
                reset();
            }else if((posicoes[0][2] == posicoes[1][1] && posicoes[1][1] == posicoes[2][0]) && posicoes[1][1] != ""){
                mostrarVencedor(true);
                reset();
            }else if(contadorJogadas == 9){
                JOptionPane.showMessageDialog(null,"Deu Velha!");
                reset();
        }
        }
        
        
    }
    
    
    
    public void reset(){
        desabilitarBotoes();
        mostrarBotoesQuemComeca();
        setarMatrizVazia();
        jtQuemComeca.setText("");
        contadorJogadas = 0;
        painelQuemComeca.requestFocus();
        
        
    }
    
    public void mostrarVencedor(boolean v){
        
        String vencedor;
        if(jtQuemComeca.getText().equals("O")){
            vencedor = "X";
        }else{
            vencedor = "O";
        }
        
        
        if(v == true){     
            jtQuemComeca.setText("");
            JOptionPane.showMessageDialog(null, "O jogador " + vencedor + " Venceu!");
        }else;   
    }
    
    public String atualizarJogador(int y, int x){
        String jogador;
        if(contador % 2 == 0){     
            jogador = "O";
        }else{      
            jogador = "X";
        }
        contador++;
        attJogada();
        return jogador;
    }
    
    public void attJogada(){
        if(jtQuemComeca.getText().equals("X")){
            jtQuemComeca.setText("O");
        }else{
            jtQuemComeca.setText("X");
        }
    }
    
    public void desabilitarBotoes(){
        btn00.setText("");btn01.setText("");btn02.setText("");
        btn10.setText("");btn11.setText("");btn12.setText("");
        btn20.setText("");btn21.setText("");btn22.setText("");
        
        btn00.setSelected(false);btn01.setSelected(false);btn02.setSelected(false);
        btn10.setSelected(false);btn11.setSelected(false);btn12.setSelected(false);
        btn20.setSelected(false);btn21.setSelected(false);btn22.setSelected(false);
        
        btn00.setEnabled(false);btn01.setEnabled(false);btn02.setEnabled(false);
        btn10.setEnabled(false);btn11.setEnabled(false);btn12.setEnabled(false);
        btn20.setEnabled(false);btn21.setEnabled(false);btn22.setEnabled(false);    
    }
    
    public void habilitarBotoes(){
        btn00.setEnabled(true);btn01.setEnabled(true);btn02.setEnabled(true);
        btn10.setEnabled(true);btn11.setEnabled(true);btn12.setEnabled(true);
        btn20.setEnabled(true);btn21.setEnabled(true);btn22.setEnabled(true);
    }
    public void desmarcarBotoesQuemComeca(){
       qcX.setSelected(false);
       qcO.setSelected(false);
    }
    
    public void esconderBotoesQuemComeca(){
        desmarcarBotoesQuemComeca();
        painelQuemComeca.setVisible(false);
    }
    
    public void mostrarBotoesQuemComeca(){
        desmarcarBotoesQuemComeca();
        painelQuemComeca.setVisible(true);
    }
    
    
    
    public void escolherQuemComeca(){
        if(qcO.isSelected()){
            contador = 0;
        }else if (qcX.isSelected()){
            contador = 1;
        }else{
            JOptionPane.showMessageDialog(null, "algo deu errado.");
        }
    }
    public void mostrarQuemComeca(){
        if(contador % 2 == 0){
            jtQuemComeca.setText("O");
        }
        else{
            jtQuemComeca.setText("X");
        }
    }
   
    private void qcXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qcXActionPerformed
        // Desmarca os dois botões e depois marca so o clicado
        desmarcarBotoesQuemComeca();
        qcX.setSelected(true);
        escolherQuemComeca();
        mostrarQuemComeca();
    }//GEN-LAST:event_qcXActionPerformed

    private void qcOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qcOActionPerformed
        // Desmarca os dois botões e depois marca so o clicado
        desmarcarBotoesQuemComeca();
        qcO.setSelected(true);
        escolherQuemComeca();
        mostrarQuemComeca();
    }//GEN-LAST:event_qcOActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // Botão para começar a partida
        if(!qcO.isSelected() && !qcX.isSelected()){
            JOptionPane.showMessageDialog(null, "Por favor selecione quem deve começar ( X ou O )");
        }else{
            txtVez.setVisible(true);
            escolherQuemComeca();
            esconderBotoesQuemComeca();
            habilitarBotoes();
        }
        
        
        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn00ActionPerformed
        btn00.setText(atualizarJogador(0, 0));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn00ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
        btn01.setText(atualizarJogador(0, 1));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        btn02.setText(atualizarJogador(0, 2));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        btn10.setText(atualizarJogador(1, 0));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        btn11.setText(atualizarJogador(1, 1));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        btn12.setText(atualizarJogador(1, 2));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        btn20.setText(atualizarJogador(2, 0));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        btn21.setText(atualizarJogador(2, 1));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn22ActionPerformed
        btn22.setText(atualizarJogador(2, 2));
        atualizarMatriz();
        testarVencedor();
    }//GEN-LAST:event_btn22ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn00;
    private javax.swing.JToggleButton btn01;
    private javax.swing.JToggleButton btn02;
    private javax.swing.JToggleButton btn10;
    private javax.swing.JToggleButton btn11;
    private javax.swing.JToggleButton btn12;
    private javax.swing.JToggleButton btn20;
    private javax.swing.JToggleButton btn21;
    private javax.swing.JToggleButton btn22;
    private javax.swing.JButton btnStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtQuemComeca;
    private javax.swing.JPanel painelQuemComeca;
    private javax.swing.JRadioButton qcO;
    private javax.swing.JRadioButton qcX;
    private javax.swing.JLabel txtVez;
    // End of variables declaration//GEN-END:variables
}
